# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.TextField(help_text='The processed locality string', max_length=2000)),
                ('locality_parts', django.contrib.postgres.fields.jsonb.JSONField()),
                ('original_locality', models.TextField(help_text='The original locality string', max_length=2000)),
                ('location_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('feature_type', models.CharField(choices=[('T', 'town'), ('M', 'mountain'), ('R', 'railway'), ('F', 'farm'), ('P', 'park'), ('U', 'unknown')], default='U', max_length=1)),
            ],
        ),
    ]
