# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Georeference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.TextField(help_text='The processed locality string', max_length=2000)),
                ('locality_parts', django.contrib.postgres.fields.jsonb.JSONField()),
                ('original_locality', models.TextField(help_text='The original locality string', max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
