# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='georeference',
            name='potential_geographical_positions',
        ),
        migrations.AddField(
            model_name='georeference',
            name='potential_georeferences',
            field=models.ManyToManyField(related_name='_georeference_potential_georeferences_+', to='website.GeoReference'),
        ),
    ]
