# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160526_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('date', models.DateField(blank=True, null=True)),
                ('feature_type', models.CharField(choices=[('T', 'town'), ('M', 'mountain'), ('R', 'railway'), ('F', 'farm'), ('P', 'park'), ('U', 'unknown')], default='U', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='georeference',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The geographical location', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Location'),
        ),
    ]
