# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160823_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_database',
            field=models.BooleanField(default=False),
        ),
    ]
