# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_is_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicalposition',
            name='precision',
        ),
        migrations.AddField(
            model_name='geographicalposition',
            name='precision_m',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
