# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160526_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='date',
        ),
        migrations.AddField(
            model_name='georeference',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
