# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160527_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='buffer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='origin',
            field=models.CharField(choices=[('US', 'user'), ('GO', 'google'), ('UN', 'unknown')], default='UN', max_length=2),
        ),
    ]
