# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 12:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160527_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('feature_type', models.CharField(choices=[('T', 'town'), ('M', 'mountain'), ('R', 'railway'), ('F', 'farm'), ('P', 'park'), ('U', 'unknown')], default='U', max_length=1)),
                ('buffer', models.IntegerField(blank=True, null=True)),
                ('origin', models.CharField(choices=[('US', 'User'), ('GO', 'Google'), ('IN', 'Input'), ('UN', 'Unknown')], default='UN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LocalityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cleaned_locality', models.TextField(help_text='The processed locality string', max_length=2000)),
                ('locality', models.TextField(help_text='The original locality string', max_length=2000)),
                ('locality_parts', django.contrib.postgres.fields.jsonb.JSONField()),
                ('potential_geo_locations', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=2)),
                ('geo_location', models.ForeignKey(blank=True, help_text='The geographical location', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.GeoLocation')),
            ],
        ),
        migrations.RemoveField(
            model_name='georeference',
            name='location',
        ),
        migrations.DeleteModel(
            name='Georeference',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
