# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160608_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localityname',
            name='cleaned_locality',
        ),
        migrations.RemoveField(
            model_name='localityname',
            name='locality',
        ),
        migrations.AddField(
            model_name='localityname',
            name='locality_name',
            field=models.TextField(default='', help_text='The locality string', max_length=2000),
            preserve_default=False,
        ),
    ]
