# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160608_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='localityname',
            name='test',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
