# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_localityname_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localityname',
            name='test',
        ),
    ]
