# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_localityname_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='localityname',
            name='date',
        ),
        migrations.AddField(
            model_name='localitydate',
            name='locality_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.LocalityName'),
        ),
    ]
