# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 15:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160622_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='georeference',
            name='potential_locations',
        ),
        migrations.AddField(
            model_name='georeference',
            name='potential_geo_locations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
