# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20160622_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoLocation',
            new_name='GeographicalPosition',
        ),
        migrations.RenameField(
            model_name='georeference',
            old_name='geo_location',
            new_name='geographical_position',
        ),
        migrations.RenameField(
            model_name='georeference',
            old_name='potential_geo_locations',
            new_name='potential_geographical_positions',
        ),
    ]
