# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 13:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20160623_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicalposition',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='geographicalposition',
            name='feature_type',
            field=models.CharField(choices=[('T', 'Town'), ('R', 'Road'), ('M', 'Mountain'), ('R', 'Railway'), ('F', 'Farm'), ('P', 'Park'), ('B', 'between two places'), ('U', 'unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='geographicalposition',
            name='origin',
            field=models.CharField(choices=[('US', 'User'), ('GO', 'Google'), ('GE', 'Geocode farm'), ('IN', 'Input'), ('RQ', 'South Africa 1:500 000 Rivers'), ('RO', 'Official list of roads'), ('UN', 'Unknown'), ('LS', 'Derived from locality string')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='georeference',
            name='notes',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='georeference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
