# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20160628_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographicalposition',
            name='feature_type',
            field=models.CharField(choices=[('TO', 'Town'), ('RO', 'Road'), ('MO', 'Mountain'), ('RA', 'Railway'), ('FA', 'Farm'), ('PA', 'Park'), ('ME', 'Measurement from a place'), ('BE', 'Between two places'), ('UN', 'Unknown')], default='UN', max_length=2),
        ),
    ]
