# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20160630_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geographicalposition',
            old_name='buffer',
            new_name='precision',
        ),
        migrations.AlterField(
            model_name='geographicalposition',
            name='origin',
            field=models.CharField(choices=[('US', 'User'), ('GO', 'Google'), ('GA', 'SANBI gazetteer'), ('GE', 'Geocode farm'), ('NO', 'Nominatim'), ('IN', 'Input'), ('RQ', 'South Africa 1:500 000 Rivers'), ('RO', 'Official list of roads'), ('UN', 'Unknown'), ('LS', 'Derived from locality string')], default='UN', max_length=2),
        ),
    ]
