# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20160721_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localityname',
            name='locality_name',
            field=models.TextField(help_text='The locality string', max_length=250),
        ),
    ]
