# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20160722_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localitydate',
            name='locality_name',
        ),
        migrations.AddField(
            model_name='georeference',
            name='locality_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LocalityDate',
        ),
    ]
